language: R
sudo: false
cache: packages
r_check_args: " --as-cran --install-args=--build"
after_success:
  - R CMD INSTALL --build ${PKG_TARBALL} ;
  - Rscript -e 'covr::coveralls(type = "all")'

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gKFTaAFRAUbu5z55El97TpBpJ39GkQZxpSo8UCsXeDvNK1BaXLxLbumSjNKyQfjDM7FeRHB2VvqvF0S8VTO1jR5Wag+6uiYFxeziiste5ZC4M8sv9jdcPUb5IdHLqagkd4gPy2HWSGdYLPMtJR6rmMn1iWii23S4mgvj9i2CKhWQp9/ixI0/WdiGhh/85wiNdbfggbP7+ugzBVQMJdZ+xHS2/N8FNR7RwT1UGxveGm43oXTTTvHs/VewxfqFEkiRnetmgiPBvzWeusztIB5syoFmbHj33eXEjEST2v6znjZTUD1WgxH/aAxT0TZU/ksRaDT0Du3ZjErY1RJsWZ1WLIdS/2xsTCoQhRlYVguN8oAExMOfBz2o6nD9pYbRXmqvwRpCXDLX8l0G3YqvxoNMdCfNkDQS2V18/e3TRxGsdHhlXxRehevYwfiMoOi17zhDfMgm/hJTIaNbRb5NkHDcH5Cjvt7ARmA4LGrrECADw9vulNB+iKm31JhtHvtn7G458Kt32PJKuGzUsCXxfqQOCTpPBQc+VFyQQnuDp8d97ozZmqSX3uaXdpu81rQxQ6o6QTLvFfME2WV4KvXymHfZLHRGwB2vVWUfPmWIS4HKBWulT1W0KrLl2O4VNRNmJcJq2TaXA5kdUmPMu26a1ChyhVzK7SdhEh1fyGk6oL+KkOI=
  file_glob: true
  file: statamd*.t*gz
  on:
    tags: true    
    repo: muschellij2/statamd
